export const API_REQUEST_ISREQUESTING = 'API_REQUEST_ISREQUESTING';
export const API_REQUEST_FAIL = 'API_REQUEST_FAIL';

export const ETH_CONNECT_METAMASK_REQUESTED = 'ETH_CONNECT_METAMASK_REQUESTED';
export const ETH_CONNECT_METAMASK_SUCCEDED = 'ETH_CONNECT_METAMASK_SUCCEDED';
export const ETH_CONNECT_METAMASK_FAILED = 'ETH_CONNECT_METAMASK_FAILED';
export const ETH_CONNECT_METAMASK_CLEAR = 'ETH_CONNECT_METAMASK_CLEAR';