export const API_REQUEST_ISREQUESTING = 'API_REQUEST_ISREQUESTING';
export const API_REQUEST_FAIL = 'API_REQUEST_FAIL';

// CONNECTION CONSTANTS
export const ETH_CONNECT_METAMASK_REQUESTED = 'ETH_CONNECT_METAMASK_REQUESTED';
export const ETH_CONNECT_METAMASK_SUCCEDED = 'ETH_CONNECT_METAMASK_SUCCEDED';
export const ETH_CONNECT_METAMASK_FAILED = 'ETH_CONNECT_METAMASK_FAILED';
export const ETH_CONNECT_METAMASK_CLEAR = 'ETH_CONNECT_METAMASK_CLEAR';

// TOKEN CONSTANTS
export const ETH_TOKEN_INFORMATION_METAMASK_REQUESTED = 'ETH_TOKEN_INFORMATION_METAMASK_REQUESTED';
export const ETH_TOKEN_INFORMATION_METAMASK_SUCCEDED = 'ETH_TOKEN_INFORMATION_METAMASK_SUCCEDED';
export const ETH_TOKEN_INFORMATION_METAMASK_FAILED = 'ETH_TOKEN_INFORMATION_METAMASK_FAILED';

// TOKEN CONSTANTS
export const ETH_TOKEN_TRANSFER_REQUESTED = 'ETH_TOKEN_TRANSFER_REQUESTED';
export const ETH_TOKEN_TRANSFER_SUCCEDED = 'ETH_TOKEN_TRANSFER_SUCCEDED';
export const ETH_TOKEN_TRANSFER_FAILED = 'ETH_TOKEN_TRANSFER_FAILED';
export const ETH_TOKEN_TRANSFER_CLEAR = 'ETH_TOKEN_TRANSFER_CLEAR';

// MODAL CONSTANTS
export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';